name: ${COMPOSE_PROJECT_NAME}
services:

  mongodb:
    image: mongo:latest
    container_name: travelmongodb
    ports:
      - 27017:27017
    volumes:
      - ./db-data/mongo:/data/db

  flightapp:
    build: .
    container_name: travelApp
    ports:
      - 8080:8080
    deploy:
      mode: replicated
      replicas: 1
    environment:
      DB_URL: mongodb://mongoDB/db/travelData
    links:
      - mongodb

volumes:
  travelVol:
    name: travel_vol
